<?php

namespace Tests\Feature;

use App\Support\Url;
use Tests\TestCase;

/**
 * Every public page has exactly ONE address: the trailing-slash form
 * (https://www.droprsvp.com/en-my/kuala-lumpur/). Apache 301s the slashless form
 * to it, so a slashless internal link doesn't break anything visible — it just
 * costs a round trip and hands Google a second URL for the same page. That is
 * what splits one page's ranking in two and shows up in Search Console as a
 * duplicate, which is the whole reason these tests exist.
 *
 * The three places that have to agree are the canonical tag, the sitemap and the
 * in-app links. The first two come from App\Support\Url; the links are hand
 * written in TSX, so they're the ones that drift — hence the source scan below.
 */
class CanonicalTrailingSlashTest extends TestCase
{
    /**
     * Files whose slashless URLs are fine and must not fail the scan:
     *   * actions/ and routes/ are generated by Wayfinder from the route table,
     *     so they always come out slashless and are overwritten on every
     *     `php artisan wayfinder:generate` — they're used for form posts, and
     *     .htaccess never rewrites a POST.
     */
    private const GENERATED = ['/resources/js/actions/', '/resources/js/routes/'];

    public function test_url_helper_always_builds_a_trailing_slash(): void
    {
        $this->assertSame('/en-my/', Url::path());
        $this->assertSame('/en-my/blog/', Url::path('blog'));
        $this->assertSame('/en-my/blog/my-post/', Url::path('blog', 'my-post'));

        // Segments arriving with stray slashes must not double them up.
        $this->assertSame('/en-my/all/music/', Url::path('/all/', '/music/'));
    }

    public function test_slash_helper_preserves_queries_and_skips_files(): void
    {
        $this->assertSame('/en-my/all/', Url::slash('/en-my/all'));
        $this->assertSame('/en-my/all/', Url::slash('/en-my/all/'));

        // A query string stays put, behind the slash.
        $this->assertSame('/en-my/all/?q=jazz', Url::slash('/en-my/all?q=jazz'));

        // File-like last segments are left exactly as they are.
        $this->assertSame('/en-my/e/gig/calendar.ics', Url::slash('/en-my/e/gig/calendar.ics'));
        $this->assertSame('/sitemap.xml', Url::slash('/sitemap.xml'));
    }

    public function test_no_frontend_link_points_at_a_slashless_public_url(): void
    {
        $offenders = [];

        foreach ($this->sourceFiles() as $file) {
            $relative = str_replace(base_path(), '', str_replace('\\', '/', $file));

            foreach (self::GENERATED as $generated) {
                if (str_contains($relative, $generated)) {
                    continue 2;
                }
            }

            $lines = file($file, FILE_IGNORE_NEW_LINES);

            foreach ($lines as $i => $line) {
                foreach ($this->slashlessLinks($line) as $link) {
                    $offenders[] = $relative.':'.($i + 1).'  '.$link;
                }
            }
        }

        $this->assertSame([], $offenders, implode("\n", [
            'These links point at a slashless public URL, which 301s to the trailing-slash form.',
            'Add the slash, or build the path with lp() from resources/js/lib/routes.ts:',
            '',
            ...$offenders,
            '',
        ]));
    }

    /**
     * Pull navigation targets out of one line of TSX and return the ones missing
     * the canonical slash. Only navigation is checked — an href, or a path handed
     * to router.get()/router.visit(), i.e. the things a crawler can follow.
     * form.post() targets are deliberately left out: .htaccess never rewrites a
     * POST, so those stay on the slashless path.
     */
    private function slashlessLinks(string $line): array
    {
        $prefix = '/'.Url::LOCALE;
        $found = [];

        // href="/en-my/…"  |  href={`/en-my/…`}  |  router.get('/en-my/…'
        $pattern = '~(?:href=|router\.(?:get|visit|replace)\()\s*\{?\s*[\'"`]('.preg_quote($prefix, '~').'[^\'"`]*)[\'"`]~';

        preg_match_all($pattern, $line, $matches, PREG_SET_ORDER);

        foreach ($matches as $match) {
            $url = $match[1];

            // Strip the query/fragment — the slash belongs before them.
            $path = preg_split('/[?#]/', $url)[0];

            // A template placeholder or a file-like last segment is exempt.
            $last = substr($path, (int) strrpos($path, '/') + 1);

            if (str_ends_with($path, '/') || str_contains($last, '.')) {
                continue;
            }

            $found[] = $url;
        }

        return $found;
    }

    /** Every .ts/.tsx file under resources/js. */
    private function sourceFiles(): array
    {
        $directory = new \RecursiveDirectoryIterator(resource_path('js'), \FilesystemIterator::SKIP_DOTS);
        $files = [];

        foreach (new \RecursiveIteratorIterator($directory) as $file) {
            if (in_array($file->getExtension(), ['ts', 'tsx'], true)) {
                $files[] = $file->getPathname();
            }
        }

        return $files;
    }
}
